/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2013-05-18 13:31:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.front;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import org.essilab.module.user.model.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <a href=\"index\" id=\"logo\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/logo-mini.png\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"search-form\" action=\"userpage\">\r\n");
      out.write("            <input type=\"text\" name=\"search\" placeholder=\"Rechercher une personne ou un restaurant...\">\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\" class=\"no-text toggle-notif\"><i class=\"icon-info-sign\"></i><span class=\"notif\">3</span></a></li>\r\n");
      out.write("                <li class=\"current\"><a href=\"index\"><i class=\"icon-home\"></i> Accueil</a></li>\r\n");
      out.write("                <li><a href=\"restaurants\"><i class=\"icon-map-marker\"></i>Les restaurants</a></li>\r\n");
      out.write("                <li><a href=\"mypage\"><i class=\"icon-user\"></i>Mon profil</a></li>\r\n");
      out.write("                <li><a href=\"message\" class=\"no-text\"><i class=\"icon-envelope\"></i><span class=\"notif\">12</span></a></li>\r\n");
      out.write("                <li><a href=\"homepage\" class=\"no-text\"><i class=\"icon-off\"></i></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"notifications\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"red\">Alexandra Martin</span> a proposÃ© une annonce.<br>\r\n");
      out.write("                        <span class=\"message-date\">28/02/2013 Ã  14h42</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"red\">RÃ©my Hannequin</span> souhaite devenir votre ami.<br>\r\n");
      out.write("                        <span class=\"message-date\">28/02/2013 Ã  14h42</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"red\">Pierre Grimaud</span> a proposÃ© une annonce.<br>\r\n");
      out.write("                        <span class=\"message-date\">28/02/2013 Ã  14h42</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"red\">Romain Deligny</span> a proposÃ© une annonce.<br>\r\n");
      out.write("                        <span class=\"message-date\">28/02/2013 Ã  14h42</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section id=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- start: Map -->\r\n");
      out.write("    <div style=\"position:relative;\">\r\n");
      out.write("\r\n");
      out.write("        <!-- starts: Google Maps -->\r\n");
      out.write("        <div id=\"googlemaps-container-top\"></div>\r\n");
      out.write("        <div id=\"googlemaps\" class=\"google-map google-map-full\"></div>\r\n");
      out.write("        <div id=\"googlemaps-container-bottom\"></div>\r\n");
      out.write("        <!-- end: Google Maps -->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"closest-users\">\r\n");
      out.write("            <h3>Utilisateurs proches de vous</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"user\">\r\n");
      out.write("                    <a href=\"announcement\">\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/users/alexandra.jpg\" width=\"40\" height=\"40\" class=\"avatar\" alt=\"\">\r\n");
      out.write("                        <span class=\"user-title\">Alexandra Martin</span>\r\n");
      out.write("                        <span class=\"user-time\">12H - 13H</span>\r\n");
      out.write("                        <span class=\"user-tags\">#communication #musique #badminton</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"user\">\r\n");
      out.write("                    <a href=\"announcement\">\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/users/herve.jpg\" width=\"40\" height=\"40\" class=\"avatar\" alt=\"\">\r\n");
      out.write("                        <span class=\"user-title\">HervÃ© Tran</span>\r\n");
      out.write("                        <span class=\"user-time\">13H - 14H30</span>\r\n");
      out.write("                        <span class=\"user-tags\">#multimedia #guitare #blues</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"user\">\r\n");
      out.write("                    <a href=\"announcement\">\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/users/pierre.jpg\" width=\"40\" height=\"40\" class=\"avatar\" alt=\"\">\r\n");
      out.write("                        <span class=\"user-title\">Pierre Grimaud</span>\r\n");
      out.write("                        <span class=\"user-time\">13H - 14H</span>\r\n");
      out.write("                        <span class=\"user-tags\">#informatique #chat</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"user\">\r\n");
      out.write("                    <a href=\"announcement\">\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/users/romain.jpg\" width=\"40\" height=\"40\" class=\"avatar\" alt=\"\">\r\n");
      out.write("                        <span class=\"user-title\">Romain Deligny</span>\r\n");
      out.write("                        <span class=\"user-time\">12H - 13H30</span>\r\n");
      out.write("                        <span class=\"user-tags\">#infirmier #football</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end: Map -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper home\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-container\">\r\n");
      out.write("            <div class=\"col-2\">\r\n");
      out.write("                <h2>Recherche avancÃ©e</h2>\r\n");
      out.write("                <form id=\"user-search-form\" action=\"announcementsearch\">\r\n");
      out.write("                    <p>\r\n");
      out.write("                        <label for=\"time-start\"><strong><i class=\"icon-time\"></i> Quand ? </strong></label>\r\n");
      out.write("                        De <input type=\"text\" id=\"time-start\"> Ã  <input type=\"text\" id=\"time-end\" >\r\n");
      out.write("                        <input type=\"submit\" class=\"btn\" value=\"Trouver\">\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        <label for=\"interests\"><strong><i class=\"icon-heart\"></i> GoÃ»ts / IntÃ©rÃªts</strong></label>\r\n");
      out.write("                        <input type=\"text\" id=\"interests\">\r\n");
      out.write("                    </p>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"current-user\" class=\"col-1\">\r\n");
      out.write("                <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/users/herve.jpg\" width=\"64\" height=\"64\" class=\"avatar\" alt=\"\">\r\n");
      out.write("                <h3><a href=\"#\" class=\"black\">HervÃ© Tran</a></h3>\r\n");
      out.write("                <span class=\"user-tags\"><a href=\"#\">#multimedia</a> <a href=\"#\">#guitare</a> <a href=\"#\">#blues</a></span>\r\n");
      out.write("                <span><a href=\"announcementcreate\" class=\"btn\"><i class=\"icon-pencil\"></i> Poster une annonce</a></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-2\">\r\n");
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("\r\n");
      out.write("            <h2>Ã dÃ©couvrir</h2>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"featured-restaurants\">\r\n");
      out.write("                <div class=\"restaurant\">\r\n");
      out.write("                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/restaurants/ocinq.jpg\" title=\"Restaurant Ocinq\" alt=\"\">\r\n");
      out.write("                    <div class=\"restaurant-infos\">\r\n");
      out.write("                        <a href=\"#\" title=\"Restaurant Ocinq\">\r\n");
      out.write("                            <h3>Restaurant Ocinq</h3>\r\n");
      out.write("                            <p>SituÃ© Ã  quelques pas de Montparnasse, rue de la GaÃ®tÃ©, le restaurant Ocinq vous accueille dans un cadre exceptionnel : dÃ©coration moderne aux teintes chaleureuses, ambiance lounge, large baie vitrÃ©e, il a tout pour plaire !</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"restaurant\">\r\n");
      out.write("                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/restaurants/creperie-framboise.jpg\" title=\"CrÃªperie Framboise\" alt=\"\">\r\n");
      out.write("                    <div class=\"restaurant-infos\">\r\n");
      out.write("                        <a href=\"#\" title=\"CrÃªperie Framboise\">\r\n");
      out.write("                            <h3>CrÃªperie Framboise</h3>\r\n");
      out.write("                            <p>La CrÃªperie Framboise, situÃ©e dans le 8Ã¨me arrondissement de Paris, Ã  deux pas du rond-point des Champs-ÃlysÃ©es, vous invite pour une pause gourmande dans un cadre Ã©lÃ©gant, moderne et trÃ¨s lumineux. </p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"restaurant\">\r\n");
      out.write("                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/restaurants/vingt-vins-dart.jpg\" title=\"Vingt vins d'art\" alt=\"\">\r\n");
      out.write("                    <div class=\"restaurant-infos\">\r\n");
      out.write("                        <a href=\"#\" title=\"Vingt vins d'art\">\r\n");
      out.write("                            <h3>Vingt vins d'art</h3>\r\n");
      out.write("                            <p>Dans le Marais, entre les mÃ©tros Saint-Paul et Pont Marie, le Vingt vins d'art a ouvert ses portes tout rÃ©cemment. Ã la fois bar Ã  (trÃ¨s bons) vins, restaurant et galerie d'art, le lieu propose aussi quelques concerts pour des soirÃ©es chaudement recommandÃ©es !</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-1\">\r\n");
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("\r\n");
      out.write("            <h2>Meet For Meal</h2>\r\n");
      out.write("            <p>\r\n");
      out.write("                Le principe du site est simple: Trouver un partenaire pour partager un repas.\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                Vous Ãªtes seul ce midi (/soir) ? Recherchez un partenaire aux alentours afin de partager un moment ensemble autour dâun repas. Vous pouvez effectuer une recherche par type de restaurant ou par tranche horaires et choisir, parmi la liste des personnes libres, celle qui vous intÃ©resse ! La visibilitÃ© de ses centres dâintÃ©rÃªts vous aidera Ã  choisir un sujet de conversation.\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                Personne ne vous intÃ©resse ? Postez votre propre annonce !\r\n");
      out.write("                La recherche de partenaire est effectuÃ©e dans un rayon de 1km aux alentours de votre gÃ©olocalisation.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-2\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-1\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-left\">\r\n");
      out.write("            <h3>Ã propos de Meet For Meal</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.<br>\r\n");
      out.write("                Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-middle\">\r\n");
      out.write("            <h3>Contactez-nous</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                <strong>Meet For Meal</strong><br>\r\n");
      out.write("                61 rue lafayette<br>\r\n");
      out.write("                93100 Rue Rapatal<br>\r\n");
      out.write("                FRANCE<br>\r\n");
      out.write("                <a href=\"mailto:contact@meetformeal.com\">contact@meetformeal.com</a>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-right\">\r\n");
      out.write("\r\n");
      out.write("            <h3>Suivez-nous</h3>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"footer-menu-back-to-top\">\r\n");
      out.write("                <a href=\"#\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                Nos pages Facebook et Twitter seront bientÃ´t disponibles !\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"copyright\">\r\n");
      out.write("            <p>\r\n");
      out.write("                &copy; 2013, Meet For Meal.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://maps.googleapis.com/maps/api/js?sensor=false\"></script>\r\n");
      out.write("<!-- build:js scripts/main.js -->\r\n");
      out.write("<script id=\"require-js\" data-params='{\"foursquareCategories\":[{\"name\":\"Boulangerie\",\"id\":\"4bf58dd8d48988d16a941735\"},{\"name\":\"Brasserie\",\"id\":\"50327c8591d4c4b30a586d5d\"},{\"name\":\"Lieu servant des hamburgers\",\"id\":\"4bf58dd8d48988d16c941735\"},{\"name\":\"Restaurant chinois\",\"id\":\"4bf58dd8d48988d145941735\"},{\"name\":\"CafÃ©-restaurant\",\"id\":\"4bf58dd8d48988d147941735\"},{\"name\":\"Fast-food\",\"id\":\"4bf58dd8d48988d16e941735\"},{\"name\":\"Restaurant franÃ§ais\",\"id\":\"4bf58dd8d48988d10c941735\"},{\"name\":\"Restaurant grec\",\"id\":\"4bf58dd8d48988d10e941735\"},{\"name\":\"Restaurant indien\",\"id\":\"4bf58dd8d48988d10f941735\"},{\"name\":\"Restaurant japonais\",\"id\":\"4bf58dd8d48988d111941735\"},{\"name\":\"Restaurant corÃ©en\",\"id\":\"4bf58dd8d48988d113941735\"},{\"name\":\"Pizzeria\",\"id\":\"4bf58dd8d48988d1ca941735\"},{\"name\":\"Sandwicherie\",\"id\":\"4bf58dd8d48988d1c5941735\"},{\"name\":\"Restaurant de fruits de mer\",\"id\":\"4bf58dd8d48988d1ce941735\"},{\"name\":\"Snack\",\"id\":\"4bf58dd8d48988d1c7941735\"},{\"name\":\"Restaurant-grill\",\"id\":\"4bf58dd8d48988d1cc941735\"},{\"name\":\"Bar Ã  sushis\",\"id\":\"4bf58dd8d48988d1d2941735\"},{\"name\":\"Bar Ã  tapas\",\"id\":\"4bf58dd8d48988d1db931735\"},{\"name\":\"Restaurant thaÃ¯landais\",\"id\":\"4bf58dd8d48988d149941735\"},{\"name\":\"Restaurant turc\",\"id\":\"4f04af1f2fb6e1c99f3db0bb\"},{\"name\":\"Restaurant vÃ©gÃ©tarien/vÃ©gÃ©talien\",\"id\":\"4bf58dd8d48988d1d3941735\"}]}' data-main=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/main\" src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/require.js\"></script>\r\n");
      out.write("<!-- endbuild -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
