/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2013-05-15 20:35:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class restaurants_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <a href=\"index\" id=\"logo\"><img src=\"/meetformeal/res/styles/default/img/logo-mini.png\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"search-form\">\r\n");
      out.write("            <input type=\"text\" name=\"search\" placeholder=\"Rechercher une personne ou un restaurant...\">\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\" class=\"no-text toggle-notif\"><i class=\"icon-info-sign\"></i><span class=\"notif\">3</span></a></li>\r\n");
      out.write("                <li><a href=\"index\"><i class=\"icon-home\"></i> Accueil</a></li>\r\n");
      out.write("                <li class=\"current\"><a href=\"restaurants\"><i class=\"icon-map-marker\"></i>Les restaurants</a></li>\r\n");
      out.write("                <li><a href=\"mypage\"><i class=\"icon-user\"></i>Mon profil</a></li>\r\n");
      out.write("                <li><a href=\"message\" class=\"no-text\"><i class=\"icon-envelope\"></i><span class=\"notif\">12</span></a></li>\r\n");
      out.write("                <li><a href=\"homepage\" class=\"no-text\"><i class=\"icon-off\"></i></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"notifications\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"red\">Alexandra Martin</span> a proposÃ© une annonce.<br>\r\n");
      out.write("                        <span class=\"message-date\">28/02/2013 Ã  14h42</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"red\">RÃ©my Hannequin</span> souhaite devenir votre ami.<br>\r\n");
      out.write("                        <span class=\"message-date\">28/02/2013 Ã  14h42</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"red\">Pierre Grimaud</span> a proposÃ© une annonce.<br>\r\n");
      out.write("                        <span class=\"message-date\">28/02/2013 Ã  14h42</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"red\">Romain Deligny</span> a proposÃ© une annonce.<br>\r\n");
      out.write("                        <span class=\"message-date\">28/02/2013 Ã  14h42</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section id=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- start: Map -->\r\n");
      out.write("    <div id=\"restaurant-map\" style=\"position:relative;\">\r\n");
      out.write("\r\n");
      out.write("        <!-- starts: Google Maps -->\r\n");
      out.write("        <div id=\"googlemaps-container-top\"></div>\r\n");
      out.write("        <div id=\"googlemaps\" class=\"google-map google-map-full\"></div>\r\n");
      out.write("        <div id=\"googlemaps-container-bottom\"></div>\r\n");
      out.write("        <!-- end: Google Maps -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end: Map -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <div id=\"map-action-bar\">\r\n");
      out.write("            <div class=\"actions\">\r\n");
      out.write("                <button class=\"btn find-venues\"><i class=\"icon-search\"></i>Rechercher</button>\r\n");
      out.write("                <button class=\"btn check-all\"><i class=\"icon-check\"></i>Tout cocher</button>\r\n");
      out.write("                <button class=\"btn uncheck-all\"><i class=\"icon-remove\"></i>Tout dÃ©cocher</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"categories\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-3\">\r\n");
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("\r\n");
      out.write("            <h2>Les restaurants autour de vous</h2>\r\n");
      out.write("            <ul id=\"search-result\">\r\n");
      out.write("                <li class=\"featured\">\r\n");
      out.write("                    <img src=\"https://foursquare.com/img/categories_v2/food/sandwiches_bg_32.png\" class=\"restaurant-category\">\r\n");
      out.write("                    <p class=\"restaurant-description\">\r\n");
      out.write("                        <span><strong class=\"title red\">BALT</strong></span><br>\r\n");
      out.write("                        <span>CatÃ©gorie : <strong>Sandwicherie</strong></span><br>\r\n");
      out.write("                        <span>Adresse : <strong>15, rue Monsigny Paris (75002) </strong></span><br>\r\n");
      out.write("                        <span>&laquo; Les sandwichs Balt doivent beaucoup Ã  la baguette Julien. Ils sont Ã  composer soi-mÃªme : rosbif, Åuf dur Ã©crasÃ©, poivron marinÃ© ou mayonnaise au basilic etc. &raquo;</span><br>\r\n");
      out.write("                        <a href=\"#\" class=\"btn\"><i class=\"icon-eye-open icon-red\"></i>Consulter</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"https://foursquare.com/img/categories_v2/nightlife/bar_bg_32.png\" class=\"restaurant-category\">\r\n");
      out.write("                    <p class=\"restaurant-description\">\r\n");
      out.write("                        <span><strong class=\"title red\">2 bis</strong></span><br>\r\n");
      out.write("                        <span>CatÃ©gorie : <strong>Bar / Sandwicherie</strong></span><br>\r\n");
      out.write("                        <span>Adresse : <strong>2 bis rue des Ecoles (75005) </strong></span><br>\r\n");
      out.write("                        <span>&laquo; La pinte la moins chÃ¨re de Paris &raquo;</span><br>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"https://foursquare.com/img/categories_v2/food/sandwiches_bg_32.png\" class=\"restaurant-category\">\r\n");
      out.write("                    <p class=\"restaurant-description\">\r\n");
      out.write("                        <span><strong class=\"title red\">BALT</strong></span><br>\r\n");
      out.write("                        <span>CatÃ©gorie : <strong>Sandwicherie</strong></span><br>\r\n");
      out.write("                        <span>Adresse : <strong>15, rue Monsigny Paris (75002) </strong></span><br>\r\n");
      out.write("                        <span>&laquo; Les sandwichs Balt doivent beaucoup Ã  la baguette Julien. Ils sont Ã  composer soi-mÃªme : rosbif, Åuf dur Ã©crasÃ©, poivron marinÃ© ou mayonnaise au basilic etc. &raquo;</span><br>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"https://foursquare.com/img/categories_v2/nightlife/bar_bg_32.png\" class=\"restaurant-category\">\r\n");
      out.write("                    <p class=\"restaurant-description\">\r\n");
      out.write("                        <span><strong class=\"title red\">2 bis</strong></span><br>\r\n");
      out.write("                        <span>CatÃ©gorie : <strong>Bar</strong></span><br>\r\n");
      out.write("                        <span>Adresse : <strong>2 bis rue des Ecoles (75005) </strong></span><br>\r\n");
      out.write("                        <span>&laquo; La pinte la moins chÃ¨re de Paris &raquo;</span><br>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-1\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-2\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-1\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-left\">\r\n");
      out.write("            <h3>Ã propos de Meet For Meal</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.<br>\r\n");
      out.write("                Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-middle\">\r\n");
      out.write("            <h3>Contactez-nous</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                <strong>Meet For Meal</strong><br>\r\n");
      out.write("                61 rue lafayette<br>\r\n");
      out.write("                93100 Rue Rapatal<br>\r\n");
      out.write("                FRANCE<br>\r\n");
      out.write("                <a href=\"mailto:contact@meetformeal.com\">contact@meetformeal.com</a>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-right\">\r\n");
      out.write("\r\n");
      out.write("            <h3>Suivez-nous</h3>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"footer-menu-back-to-top\">\r\n");
      out.write("                <a href=\"#\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                Nos pages Facebook et Twitter seront bientÃ´t disponibles !\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"copyright\">\r\n");
      out.write("            <p>\r\n");
      out.write("                &copy; 2013, Meet For Meal.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://maps.googleapis.com/maps/api/js?sensor=false\"></script>\r\n");
      out.write("<!-- build:js scripts/main.js -->\r\n");
      out.write("<script id=\"require-js\" data-params='{\"foursquareCategories\":[{\"name\":\"Boulangerie\",\"id\":\"4bf58dd8d48988d16a941735\"},{\"name\":\"Brasserie\",\"id\":\"50327c8591d4c4b30a586d5d\"},{\"name\":\"Lieu servant des hamburgers\",\"id\":\"4bf58dd8d48988d16c941735\"},{\"name\":\"Restaurant chinois\",\"id\":\"4bf58dd8d48988d145941735\"},{\"name\":\"CafÃ©-restaurant\",\"id\":\"4bf58dd8d48988d147941735\"},{\"name\":\"Fast-food\",\"id\":\"4bf58dd8d48988d16e941735\"},{\"name\":\"Restaurant franÃ§ais\",\"id\":\"4bf58dd8d48988d10c941735\"},{\"name\":\"Restaurant grec\",\"id\":\"4bf58dd8d48988d10e941735\"},{\"name\":\"Restaurant indien\",\"id\":\"4bf58dd8d48988d10f941735\"},{\"name\":\"Restaurant japonais\",\"id\":\"4bf58dd8d48988d111941735\"},{\"name\":\"Restaurant corÃ©en\",\"id\":\"4bf58dd8d48988d113941735\"},{\"name\":\"Pizzeria\",\"id\":\"4bf58dd8d48988d1ca941735\"},{\"name\":\"Sandwicherie\",\"id\":\"4bf58dd8d48988d1c5941735\"},{\"name\":\"Restaurant de fruits de mer\",\"id\":\"4bf58dd8d48988d1ce941735\"},{\"name\":\"Snack\",\"id\":\"4bf58dd8d48988d1c7941735\"},{\"name\":\"Restaurant-grill\",\"id\":\"4bf58dd8d48988d1cc941735\"},{\"name\":\"Bar Ã  sushis\",\"id\":\"4bf58dd8d48988d1d2941735\"},{\"name\":\"Bar Ã  tapas\",\"id\":\"4bf58dd8d48988d1db931735\"},{\"name\":\"Restaurant thaÃ¯landais\",\"id\":\"4bf58dd8d48988d149941735\"},{\"name\":\"Restaurant turc\",\"id\":\"4f04af1f2fb6e1c99f3db0bb\"},{\"name\":\"Restaurant vÃ©gÃ©tarien/vÃ©gÃ©talien\",\"id\":\"4bf58dd8d48988d1d3941735\"}]}' data-main=\"/meetformeal/res/js/main\" src=\"/meetformeal/res/js/require.js\"></script>\r\n");
      out.write("<!-- endbuild -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
